
                    

<div class="well">

<form action="{{url("category/create")}}" method="post">
		<?php echo $form->render("id")?>
		<label for="name">分类名称</label>
		<?php echo $form->render("name",array("class"=>'form-control'))?>
		<div class="form-group">
		<label >是否父类</label>
		<?php echo $form->render("isParent",array("class"=>'form-control',"readonly"=>"true"))?>
		</div>

		<input type="submit" class="btn btn-default" value="提交">
	</form>


</div>
                   
    




