<div class="well">
	<form action="{{url('category/create')}}" method="post">
		<label for="name">分类名称</label>
		<?php echo $form->render("name",array("class"=>'form-control'))?>
		<div class="form-group">
		<label >是否父类</label>
		<?php echo $form->render("isParent",array("class"=>'form-control'))?>
		</div>
		<div class="form-group hidden" id="father">
		<label >父类</label>
		<?php echo $form->render("parentId",array("class"=>'form-control'))?>
		</div>
		<input type="submit" class="btn btn-default" value="提交">
	</form>


</div>

<script language="javascript" type="text/javascript"> 
$(document).ready(function(){ 
	$('#isParent').change(function(){
		if($(this).children('option:selected').val()==0){
			$('#father').removeClass("hidden");
		}
	})
})
</script>





