
                    
<div class="btn-toolbar">
    <a class="btn btn-primary" href="{{url("category/index/")}}"><i class="glyphicon glyphicon-arrow-left"></i> 返回</a>
    <a class="btn btn-primary" href="{{url("category/new/")}}<?php echo $parent->id;?>"><i class="glyphicon glyphicon-plus"></i> 新增</a>
  <div class="btn-group">
  </div>
</div>
<div class="">父类名称：<?php echo $parent->name;?>
</div>
<div class="well">
    <table class="table">
      <thead>
        <tr>
          <th>类目编号</th>
          <th>类目名称</th>
          <th style="width: 150px;">操作</th>
        </tr>
      </thead>
      <tbody>
      <?php foreach($category as $item){?>
        <tr>
          <td><?php echo $item->id;?></td>
          <td><?php echo $item->name;?></td>
          <td>
              <a href="{{url("category/edit/")}}<?php echo $item->id;?>"><i class="glyphicon glyphicon-pencil"></i></a>
              <a href="javascript:void(0)" role="button" onclick="dodel(<?php echo $item->id;?>)"><i class="glyphicon glyphicon-remove"></i></a>
            
          </td>
        </tr>
      <?php }?> 
      </tbody>
    </table>
</div>
	
</div>
	<div aria-hidden="true" aria-labelledby="myModalLabel" role="dialog" tabindex="-1" id="myModal" class="modal fade">
	    <div class="modal-dialog">
   		<div class="modal-content">
	    <div class="modal-header">
	        <button aria-hidden="true" data-dismiss="modal" class="close" type="button">×</button>
	        <h3 id="myModalLabel">Delete Confirmation</h3>
	    </div>
	    <div class="modal-body">
	        <p class="error-text"><i class="glyphicon glyphicon-exclamation-sign " style="font-size: 60px"></i>
	          <span style="position:relative;top:-20px;font-size: 20px">Are you sure you want to delete the user?</span>
	        </p>
	    </div>
	    <div class="modal-footer">
	        <button aria-hidden="true" data-dismiss="modal" class="btn">Cancel</button>
	        <a  class="btn btn-danger"  >Delete</a>
	    </div>
	    </div>
	    </div>
	</div>
	
	
<script type="text/javascript">
	function dodel(id){
	$(".btn-danger").attr('href','delete/'+id);
		$('.modal').modal('show');
	}
</script>
                   
    



