





    <div class="container">
       <div class="row">
          <div class="col-lg-4 col-lg-offset-4 login">
            <div class="text-center logo">
              <img src="http://static.xidibuy.com/represent/static/global/images/1.0.0/logo.png">
            </div>
            <form id="loginForm" action="">
              <input id="email" class="input" type="email" placeholder="邮箱" name="name">
              <input id="password" class="input" type="password" placeholder="密码" name="password">
              <button id="loginBtn" class="input btn btn-primary btn-lg">登录</button>
             </form>
          </div>
        </div>
    </div>

   
    <script type="text/javascript">
      $("#loginBtn").on("click",function(e){
        e.preventDefault();
        login();
      })
      function login(){
        $.ajax({
            type:"post",
            url:"./ajaxLogin",
            dataType:"json",
            data: $("#loginForm").serialize(),
            success:function(data){
                if(data.code!='0'){
                    alert(data.msg);
                }else{
                    window.location.href="/haitao/index";
                }
            }
        })
      }
    </script>
     <link rel="stylesheet" href="../css/login.css">


