
<div class="navbar navbar-default navbar-fixed-top navbar-inverse">
	<div class="container-fluid">
	     Brand and toggle get grouped for better mobile display 
	    <div class="navbar-header">
	      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
	        <span class="sr-only">运营后台</span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	      </button>
	      <a class="navbar-brand" href="#">运营后台</a>
	    </div>
	    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
     		 <ul class="nav navbar-nav navbar-right">
        		<li class="active"><a href="#">XXX <span class="sr-only">(current)</span></a></li>
       			<li><a href="#">退出</a></li>
       		 </ul>
       	</div>	 
	 </div>
</div>
