<div class="sidebar-nav">
        <a href="#dashboard-user" class="nav-header" data-toggle="collapse">
        <i class="glyphicon glyphicon-user"></i> 用户管理</a>
        <ul id="dashboard-user" class="nav nav-list collapse ">
            <li><a class="menu" href="{{url("invoices/profile")}}">修改密码</a></li>
            <li ><a class="menu"  href="users.html">角色管理</a></li>
            <li ><a class="menu"  href="user.html">权限管理</a></li>
        </ul>
        <a href="#dashboard-menu" class="nav-header" data-toggle="collapse">
        <i class="glyphicon glyphicon-gift"></i> 商品管理</a>
        <ul id="dashboard-menu" class="nav nav-list collapse ">
            <li><a class="menu" href="index.html">品牌管理</a></li>
            <li ><a class="menu"  href="{{url("category/index")}}">类目管理</a></li>
            <li ><a class="menu"  href="{{url("products/index")}}">商品管理</a></li>
        </ul>
       
    </div>