
<ul class="nav  nav-stacked nav-sidebar">

  <li role="presentation" class="" >
  	<a href="#collapseExample" data-toggle="collapse" aria-expanded="false" aria-controls="collapseExample">Home</a>
  </li>
  	<div class="collapse" id="collapseExample">
	 	<ul class="list-group">
		  <li class="{{url("goods/index")}}”"><a>商品管理</a></li>
		  <li class="list-group-item">Dapibus ac facilisis in</li>
		  <li class="list-group-item">Morbi leo risus</li>
		  <li class="list-group-item">Porta ac consectetur ac</li>
		  <li class="list-group-item">Vestibulum at eros</li>
		 </ul>
	</div>
  <li role="presentation"><a href="#">Profile</a></li>
  <li role="presentation"><a href="#">Messages</a></li>

</ul>
<ul class="nav nav-list">
	
</ul>