<div class="navbar navbar-inverse navbar-fixed-top">
    		<a class="brand" style=" margin-left:10px;" href="/" >运营后台</a>
    		<div class="nav-collapse collapse">
    			<ul style="margin-right: 10px;" class="nav pull-right">
                    <li><a href="javascript:void(0)">xxx</a></li>
                    <li><a href="/index/password">修改密码</a></li>
                    <li><a href="/index/logout">退出</a></li>
                </ul>	
			</div>
</div>